--1.RETRIEVE A LIST OF MANAGERS
SELECT DISTINCT (E2.ENAME) FROM EMP E1 JOIN EMP E2 ON E1.MGR_ID = E2.EMPNO

--2.FIND OUT THE NAMES AND SALARIES OF ALL EMPLOYEE EARNING MORE THAN 1000 PER MONTH
SELECT ENAME, SAL FROM EMP WHERE SAL > 1000

--3.DISPLAY THE NAMES AND SALARIES OF ALL EMPLOYEES EXCEPT JAMES
SELECT ENAME, SAL FROM EMP WHERE ENAME NOT LIKE 'JAMES'

--4.FIND OUT THE DETAILS OF EMPLOYEES WHOSE NAMES BEGIN WIHT 'S'
SELECT * FROM EMP WHERE ENAME LIKE 'S%'

--5.FIND OUT NAMES OF ALL EMPLOYEES THAT HAVE 'A' ANYWHERE IN THEIR NAME.
SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%'

--6.FIND OUT NAMES OF ALL EMPLOYEES THAT HAVE 'L' AS THEIR THIRD CHARACTER IN THEIR NAME.
SELECT ENAME FROM EMP WHERE ENAME LIKE '__L%'

--7.COMPUTE DAILY SALARY OF JONES
SELECT SAL/30 AS 'DAILY SALARY' FROM EMP WHERE ENAME = 'JONES' 

--8.CALCULATE THE TOTAL MONTHLY SALARY OF ALL EMPLOYEES.
SELECT SUM(SAL) AS 'TOTAL MONTHLY SALARY' FROM EMP

--9.PRINT THE AVERAGE ANNUAL SALARY.
SELECT AVG(SAL*12) AS 'AVERAGE ANNUAL SALARY' FROM EMP

--10.SELECT THE NAME, JOB, SALARY, DEPARTMENT NUMBER, OF ALL EMPLOYEES EXCEPT SALESMAN FROM DEPARTMENT NUMBER 30.
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB NOT LIKE 'SALESMAN' AND DEPTNO !=30

--11. LIST UNIQUE DEPARTMENTS OF EMP TABLE.
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMP)

--12.LIST THE NAME AND SALARY OF EMPLOYEES WHO EARN MORE THAN 1500 AND ARE IN DEPARTMENT 10 OR 30.
--LABEL THE COLUMNS EMPLOYEE AND MONTHLY SALARY RESPECTIVELY.
SELECT ENAME AS 'EMPLOYEE NAME', SAL AS 'MONTHLY SALARY' FROM EMP WHERE SAL > 1500 AND (DEPTNO = 10 OR DEPTNO = 30)

--13.DISPLAY THE NAME, JOB AND SALARY OF EMPLOYEES WHOSE JOB IS MANAGER OR ANALYST AND THEIR SALARY IS NOT EQUAL TO 1000, 3000, OR 5000.
SELECT ENAME, JOB, SAL FROM EMP WHERE (JOB LIKE 'MANAGER' OR JOB LIKE 'ANALYST') AND (SAL NOT IN (1000, 3000, 5000))

--14. DISPLAY THE NAME, SALARY AND COMMISSION FOR ALL EMPLOYEES WHOSE COMMISION AMOUNT IS GREATER THAN THEIR SALARY INCREASED BY 10%.
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > (SAL + 0.1*SAL)

--15. DISPLAY THE NAME OF ALL EMPLOYEES WHO HAVE TWO Ls IN THEIR NAME AND ARE IN DEPARTMET 30 OR THEIR MANAGER IS 7782.
SELECT ENAME FROM EMP WHERE ENAME LIKE '%L%L%' AND (DEPTNO = 30 OR MGR_ID = 7782)

--16.DISPLAY THE NAMES OF EMPLOYEES WITH EXPERIENCE OF OVER 10 YEARS AND UNDER 20 YRS.(USED 40 INSTEAD OF 20 AS 10-20 YRS EXPIRENCE COUNT IS 0)
--   COUNT THE TOTAL NUMBER OF EMPLOYEES.
SELECT COUNT(ENAME) FROM EMP WHERE ENAME IN (SELECT ENAME FROM EMP WHERE 40 > DATEDIFF(YEAR, HIREDATE, GETDATE()) AND DATEDIFF(YEAR, HIREDATE, GETDATE()) > 10)

--17.RETRIEVE THE NAMES OF DEPARTMENTS IN ASCENDING ORDER AND THEIR EMPLOYEES IN DESCENDING ORDER.
SELECT D.DNAME, E.ENAME FROM DEPT D JOIN EMP E ON D.DEPTNO = E.DEPTNO ORDER BY D.DEPTNO ASC ,E.ENAME DESC 

--18.FIND OUT EXPERIENCE OF MILLER.
SELECT DATEDIFF(YEAR, HIREDATE, GETDATE()) FROM EMP WHERE ENAME = 'MILLER'
